-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS ALX_BOOK_STORE;
USE ALX_BOOK_STORE;

-- Create Authors table
CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(215) NOT NULL
);

-- Create Books table
CREATE TABLE IF NOT EXISTS BOOKS (
    BOOK_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Create Customers table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL,
    ADDRESS TEXT
);

-- Create Orders table
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Create Order_Details table
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERDETAILID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
